version: '3.7'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build:
      context: ./
      args:
        - RUBY_VERSION=3.1.2
    environment:
      - BASE_DATABASE_URL=postgresql://postgres:@db:5432/
    depends_on:
      - postgres
    entrypoint: ./entrypoint.sh
    ports:
      - 5000:3000
    volumes:
      - .:/app:cached
    tty: true
    stdin_open: true

volumes:
    postgres:
