default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV.fetch('BASE_DATABASE_URL', '') + 'blocoa_api_development' %>

test:
  <<: *default
  url: <%= ENV.fetch('BASE_DATABASE_URL', '') + 'blocoa_api_test' %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
