name: Ruby

on:
  pull_request:
    branches: [ main ]
    
env:
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/
  RAILS_ENV: test

jobs:     
  quality_checks:
    name: Quality Checks
    
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Setup test database
        run: bundle exec rails db:create && bundle exec rails db:migrate
      - name: Run RSpec
        run: bundle exec rspec
